import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <QueryProvider>
          <Toaster
            toastOptions={{
              classNames: {
                error: "bg-red-400",
                success: "border-none bg-emerald-100 text-emerald-600",
                warning: "text-yellow-400",
                info: "bg-blue-400",
              },
            }}
          />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
